#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata":{"name":"config-events", "namespace":"tekton-pipelines"}})
---
#@overlay/replace
data: #@ data.values["config-events"]
