#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata":{"name":"config-leader-election"}}),expects=2
---
#@overlay/replace
data: #@ data.values["config-leader-election"]
