#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"tekton-pipelines-controller", "namespace":"tekton-pipelines"}})
---
spec:
  #@overlay/match missing_ok=True
  replicas: #@ data.values.controllers.pipelines.replicas

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"tekton-pipelines-remote-resolvers", "namespace":"tekton-pipelines-resolvers"}})
---
spec:
  #@overlay/match missing_ok=True
  replicas: #@ data.values.controllers.resolvers.replicas

#@overlay/match by=overlay.subset({"kind":"HorizontalPodAutoscaler", "metadata":{"name":"tekton-pipelines-webhook", "namespace":"tekton-pipelines"}})
---
spec:
  minReplicas: #@ data.values.webhook.minReplicas

#@ if data.values.webhook.minReplicas >= 2:
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tekton-pipelines-webhook
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-pipelines
#@ end
