#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if data.values["config-tracing"].enabled == "true":

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"tekton-pipelines-controller", "namespace":"tekton-pipelines"}})
---
spec:
  template:
    spec:
      containers:
        #@overlay/match by="name"
        - name: tekton-pipelines-controller
          env:
            #@overlay/append
            #@ if/end data.values.opentelemetry.exporter.jaeger.username:
            - name: OTEL_EXPORTER_JAEGER_USER
              value: #@ data.values.opentelemetry.exporter.jaeger.username
            #@ if/end data.values.opentelemetry.exporter.jaeger.password:
            - name: OTEL_EXPORTER_JAEGER_PASSWORD
              value: #@ data.values.opentelemetry.exporter.jaeger.password  

#@ end
