#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"tekton-pipelines-remote-resolvers", "namespace":"tekton-pipelines-resolvers"}})
---
spec:
  template:
    spec:
      containers:
        #@overlay/match by="name"
        - name: controller
          env:
            #@overlay/match by="name"
            - name: ARTIFACT_HUB_API
              value: #@ data.values.controllers.resolvers.artifact_hub_url
            #@overlay/match by="name"
            - name: TEKTON_HUB_API
              value: #@ data.values.controllers.resolvers.tekton_hub_url
