#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata":{"name":"hubresolver-config", "namespace":"tekton-pipelines-resolvers"}}),expects=1
---
#@overlay/replace
data: #@ data.values.resolvers["hubresolver-config"]
