#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata":{"name":"bundleresolver-config", "namespace":"tekton-pipelines-resolvers"}})
---
#@overlay/replace
data: #@ data.values.resolvers["bundleresolver-config"]
