---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.50.0

#! Rebase rules explicitly define how kapp should merge resources during an update.
#! See more about the resource merge method: https://carvel.dev/kapp/docs/latest/merge-method.
rebaseRules:

#! The HorizontalPodAutoscaler updates the replicas on Deployments.
#! We want to keep that configuration between upgrades.
- path: [spec, replicas]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: apps/v1, kind: Deployment}

#! This Secret is created empty and populated by Tekton Pipelines.
- paths:
  - [data, ca-cert.pem]
  - [data, server-cert.pem]
  - [data, server-key.pem]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: Secret
      namespace: tekton-pipelines
      name: webhook-certs

#! By default, the changes applied by users to the ConfigMaps used by Tekton Pipelines
#! are persisted between upgrades.
- path: [data]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - andMatcher:
      matchers:
      - apiVersionKindMatcher: {apiVersion: v1, kind: ConfigMap}
      - hasNamespaceMatcher:
          names:
          - tekton-pipelines

#! Changes applied to the config-defaults ConfigMap directly to the cluster
#! are not persisted between upgrades.
- path: [data]
  type: copy
  sources: [new]
  resourceMatchers:
  - kindNamespaceNameMatcher: {kind: ConfigMap, namespace: tekton-pipelines, name: config-defaults}

#! When upgrading, we persist the changes applied to the ConfigMaps used by Tekton Pipelines,
#! but we want to get the new examples applied from the new version.
- path: [data, _example]
  type: remove
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: ConfigMap}
- path: [data, _example]
  type: copy
  sources: [new]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: ConfigMap}

#! This webhook configuration is populated by Tekton Pipelines.
#! We want to persist those changes between upgrades.
- paths:
  - [spec, conversion, webhook, clientConfig, service, path]
  - [spec, conversion, webhook, clientConfig, service, port]
  - [spec, names, listKind]
  - [spec, preserveUnknownFields]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: apiextensions.k8s.io/v1, kind: CustomResourceDefinition}

#! These webhook configurations are populated by Tekton Pipelines.
#! By default, we want to persist those changes between upgrades.
- paths:
  - [webhooks, {allIndexes: true}, clientConfig, service, path]
  - [webhooks, {allIndexes: true}, clientConfig, service, port]
  - [webhooks, {allIndexes: true}, matchPolicy]
  - [webhooks, {allIndexes: true}, namespaceSelector]
  - [webhooks, {allIndexes: true}, objectSelector]
  - [webhooks, {allIndexes: true}, reinvocationPolicy]
  - [webhooks, {allIndexes: true}, rules]
  - [webhooks, {allIndexes: true}, timeoutSeconds]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: admissionregistration.k8s.io/v1, kind: MutatingWebhookConfiguration}
  - apiVersionKindMatcher: {apiVersion: admissionregistration.k8s.io/v1, kind: ValidatingWebhookConfiguration}
