#@data/values-schema
---

#@schema/desc "PEM-encoded certificate data to trust TLS connections with a custom CA."
ca_cert_data: ""

#@schema/desc "Settings for the Kyverno policies."
policies:
  #@schema/desc "Whether to include the out-of-the-box Kyverno policies to validate and secure the package installation."
  include: false

#@schema/desc "Settings for the Tekton Pipelines controllers."
controllers:
  #@schema/desc "Settings for the `tekton-pipelines-controller` Deployment."
  pipelines:
    #@schema/desc "The number of replicas for the `tekton-pipelines-controller` Deployment. In order to enable high availability, it should be greater than 1."
    #@schema/validation min=1
    replicas: 1
  #@schema/desc "Settings for the `tekton-pipelines-remote-resolvers` Deployment."
  resolvers:
    #@schema/desc "The number of replicas. In order to enable high availability, it should be greater than 1."
    #@schema/validation min=1
    replicas: 1

#@schema/desc "Settings for the `tekton-pipelines-webhook` Deployment."
webhook:
  #@schema/desc "The minimum number of replicas as controlled by a HorizontalPodAutoscaler. In order to enable high availability, it should be greater than 1."
  #@schema/validation min=1, max=5
  minReplicas: 1

#@schema/desc "Settings for the OpenTelemetry support."
opentelemetry:
  #@schema/desc "Setting this flag to `true` enables the trace exporter."
  enable: false
  #@schema/desc "Settings for the OpenTelemetry exporter"
  exporter:
    #@schema/desc "Configuration for the OpenTelemetry exporter based on the Jaeger protocol."
    jaeger:
      #@schema/desc "The endpoint where the distributed tracing backend accepts OpenTelemetry traces using the Jaeger protocol."
      endpoint: ""
      #@schema/desc "The username to access the distributed tracing backend."
      username: ""
      #@schema/desc "The password/token to authenticate with the distributed tracing backend."
      password: ""

#@schema/desc "Default configuration stored in the `config-defaults` ConfigMap."
config-defaults:
  #@schema/desc "Number of minutes to use for TaskRun and PipelineRun, if none is specified."
  default-timeout-minutes: "60"
  #@schema/desc "Service account name to use for TaskRun and PipelineRun, if none is specified."
  default-service-account: "default"
  #@schema/desc "Value given to the `app.kubernetes.io/managed-by` label applied to all Pods created for TaskRuns."
  default-managed-by-label-value: "tekton-pipelines"
  #@schema/desc "Pod template to use for TaskRun and PipelineRun."
  default-pod-template: ""
  #@schema/desc "Pod template to use for affinity assistant Pods."
  default-affinity-assistant-pod-template: ""
  #@schema/desc "CloudEvents sink to be used for TaskRun, PipelineRun, CustomRun, and Run lifeycle events. If no sink is specified, no CloudEvent is generated."
  default-cloud-events-sink: ""
  #@schema/desc "Workspace configuration provided for any Workspaces that a Task declares but that a TaskRun does not explicitly provide."
  default-task-run-workspace-binding: |
    emptyDir: {}
  #@schema/desc "Maximum number of combinations from a Matrix, if none is specified."
  default-max-matrix-combinations-count: "256"
  #@schema/desc "Comma seperated environment variables that cannot be overridden by PodTemplate."
  default-forbidden-env: ""

#@schema/desc "Leader election configuration stored in the `config-leader-election` ConfigMaps and used in both Tekton Pipelines and Tekton Pipelines Resolvers."
config-leader-election:
  #@schema/desc "How long non-leaders will wait to try to acquire the lock; 15 seconds is the value used by core Kubernetes controllers."
  lease-duration: "60s"
  #@schema/desc "How long a leader will try to renew the lease before giving up; 10 seconds is the value used by core Kubernetes controllers."
  renew-deadline: "40s"
  #@schema/desc "How long the leader election client waits between tries of actions; 2 seconds is the value used by core Kubernetes controllers."
  retry-period: "10s"
  #@schema/desc "The number of buckets used to partition key space of each Reconciler. If this number is M and the replica number of the controller is N, the N replicas will compete for the M buckets. The owner of a bucket will take care of the reconciling for the keys partitioned into that bucket. The maximum value of at this time is 10."
  buckets: "1"

#@schema/desc "Logging configuration stored in the `config-logging` ConfigMaps and used in both Tekton Pipelines and Tekton Pipelines Resolvers."
config-logging:
  #@schema/desc "Configuration for the zap logger used by all Tekton containers."
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "sampling": {
        "initial": 100,
        "thereafter": 100
      },
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "timestamp",
        "levelKey": "severity",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "message",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
  #@schema/desc "Log level for the `tekton-pipelines-controller` and `tekton-pipelines-resolvers` Deployments."
  loglevel.controller: "info"
  #@schema/desc "Log level for the `tekton-pipelines-webhook` Deployment."
  loglevel.webhook: "info"

#@schema/desc "Observability configuration stored in the `config-observability` ConfigMaps and used in both Tekton Pipelines and Tekton Pipelines Resolvers."
config-observability:
  #@schema/desc "The destination for the metrics produced by the Tekton components."
  #@schema/validation one_of=["prometheus", "stackdriver"]
  metrics.backend-destination: "prometheus"
  #@schema/desc "The Stackdriver project ID. When running on GCE, application default credentials will be used and metrics will be sent to the cluster's project if this field is not provided."
  metrics.stackdriver-project-id: ""
  #@schema/desc "Whether it is allowed to send metrics to Stackdriver using 'global' resource type and custom metric type. Ignore if `backend_destination` is not `stackdriver`."
  #@schema/validation one_of=["true", "false"]
  metrics.allow-stackdriver-custom-metrics: "false"
  #@schema/desc "Level for the TaskRun metrics controlling which labels are included: (taskrun, task, namespace), (task, namespace), (namespace)."
  #@schema/validation one_of=["taskrun", "task", "namespace"]
  metrics.taskrun.level: "task"
  #@schema/desc "Duration type for the TaskRun metrics. Histogram value isn’t available when the `taskrun` level is selected."
  #@schema/validation one_of=["histogram", "lastvalue"]
  metrics.taskrun.duration-type: "histogram"
  #@schema/desc "Level for the PipelineRun metrics controlling which labels are included: (pipelinerun, pipeline, namespace), (pipeline, namespace), (namespace)."
  #@schema/validation one_of=["pipelinerun", "pipeline", "namespace"]
  metrics.pipelinerun.level: "pipeline"
  #@schema/desc "Duration type for the PipelineRun metrics. Histogram value isn’t available when the `pipelinerun` level is selected."
  #@schema/validation one_of=["histogram", "lastvalue"]
  metrics.pipelinerun.duration-type: "histogram"

#@schema/desc "Feature flags configuration stored in the `feature-flags` ConfigMap."
feature-flags:
  #@schema/desc "Setting this flag to `true` will prevent Tekton to create an Affinity Assistant for every TaskRun sharing a PVC workspace."
  #@schema/validation one_of=["true", "false"]
  disable-affinity-assistant: "false"
  #@schema/desc "Setting this flag to `true` will prevent Tekton scanning attached service accounts and injecting any credentials it finds into your Steps."
  #@schema/validation one_of=["true", "false"]
  disable-creds-init: "false"
  #@schema/desc "Setting this flag to `false` will stop Tekton from waiting for a TaskRun's sidecar containers to be running before starting the first step. This will allow Tasks to be run in environments that don't support the DownwardAPI volume type, but may lead to unintended behaviour if sidecars are used."
  #@schema/validation one_of=["true", "false"]
  await-sidecar-readiness: "true"
  #@schema/desc "This option should be set to `false` when Pipelines is running in a cluster that does not use injected sidecars such as Istio. Setting it to false should decrease the time it takes for a TaskRun to start running. For clusters that use injected sidecars, setting this option to false can lead to unexpected behavior."
  #@schema/validation one_of=["true", "false"]
  running-in-environment-with-injected-sidecars: "true"
  #@schema/desc "Setting this flag to `true` will require that any Git SSH Secret offered to Tekton must have `known_hosts` included."
  #@schema/validation one_of=["true", "false"]
  require-git-ssh-secret-known-hosts: "false"
  #@schema/desc "Setting this flag to `true` enables the use of Tekton OCI bundle. This is an experimental feature and thus should still be considered an alpha feature."
  #@schema/validation one_of=["true", "false"]
  enable-tekton-oci-bundles: "false"
  #@schema/desc "Setting this flag will determine which gated features are enabled."
  #@schema/validation one_of=["stable", "beta", "alpha"]
  enable-api-fields: "stable"
  #@schema/desc "Setting this flag to `true` enables CloudEvents for CustomRuns and Runs, as long as a CloudEvents sink is configured in the `config-defaults` ConfigMap."
  #@schema/validation one_of=["true", "false"]
  send-cloudevents-for-runs: "false"
  #@schema/desc "Setting this flag to `enforce` will enforce verification of tasks/pipelines. Failing to verify will fail the TaskRun/PipelineRun. `warn` will only log the err message and `skip` will skip the whole verification."
  #@schema/validation one_of=["enforce", "skip", "warn"]
  resource-verification-mode: "skip"
  #@schema/desc "Setting this flag to `true` enables populating the `provenance` field in TaskRun and PipelineRun status. This field contains metadata about resources used in the TaskRun/PipelineRun such as the source from where a remote Task/Pipeline definition was fetched."
  #@schema/validation one_of=["true", "false"]
  enable-provenance-in-status: "false"
  #@schema/desc "Setting this flag will determine the version for custom tasks created by PipelineRuns."
  #@schema/validation one_of=["v1alpha1", "v1beta1"]
  custom-task-version: "v1beta1"
  #@schema/desc "Setting this flag will determine how Tekton Pipelines will handle non-falsifiable provenance. If set to `spire`, then SPIRE will be used to ensure non-falsifiable provenance. If set to `none`, then Tekton will not have non-falsifiable provenance. This is an experimental feature and thus should still be considered an alpha feature."
  #@schema/validation one_of=["none", "spire"]
  enforce-nonfalsifiablity: "none"

#@schema/desc "Configuration for the Tekton Resolvers, responsible for resolving requests for Tasks and Pipelines from remote locations."
resolvers:

  #@schema/desc "Configuration for the bundle resolver stored in the `bundleresolver-config` ConfigMap."
  bundleresolver-config:
    #@schema/desc "The default name of the service account to use when constructing registry credentials."
    default-service-account: "default"
    #@schema/desc "The default resource kind to pull out of the bundle."
    #@schema/validation one_of=["pipeline", "task"]
    default-kind: "task"

  #@schema/desc "Configuration for the cluster resolver stored in the `cluster-resolver-config` ConfigMap."
  cluster-resolver-config:
    #@schema/desc "The default resource kind to fetch."
    #@schema/validation one_of=["pipeline", "task"]
    default-kind: "task"
    #@schema/desc "The default namespace to fetch resources from."
    default-namespace: ""
    #@schema/desc "A comma-separated list of namespaces which the resolver is allowed to access. Defaults to empty, meaning all namespaces are allowed."
    allowed-namespaces: ""
    #@schema/desc "A comma-separated list of namespaces which the resolver is blocked from accessing. Defaults to empty, meaning all namespaces are allowed."
    blocked-namespaces: ""

  #@schema/desc "Configuration for the git resolver stored in the `git-resolver-config` ConfigMap."
  git-resolver-config:
    #@schema/desc "The maximum amount of time a single anonymous cloning resolution may take."
    fetch-timeout: "1m"
    #@schema/desc "The git url to fetch the remote resource from when using anonymous cloning."
    default-url: "https://github.com/tektoncd/catalog.git"
    #@schema/desc "The git revision to fetch the remote resource from with either anonymous cloning or the authenticated API."
    default-revision: "main"
    #@schema/desc "The SCM type to use with the authenticated API."
    #@schema/validation one_of=["github", "gitlab", "gitea", "bitbucketserver", "bitbucketcloud"]
    scm-type: "github"
    #@schema/desc "The SCM server URL to use with the authenticated API. Not needed when using github.com, gitlab.com, or BitBucket Cloud."
    server-url: ""
    #@schema/desc "The Kubernetes secret containing the API token for the SCM provider. Required when using the authenticated API."
    api-token-secret-name: ""
    #@schema/desc "The key in the API token secret containing the actual token. Required when using the authenticated API."
    api-token-secret-key: ""
    #@schema/desc "The namespace containing the API token secret."
    api-token-secret-namespace: "default"
    #@schema/desc "The default organization to look for repositories under when using the authenticated API."
    default-org: ""

  #@schema/desc "Configuration for the hub resolver stored in the `hubresolver-config` ConfigMap."
  hubresolver-config:
    #@schema/desc "The default Tekton Hub catalog from where to pull the resource."
    default-tekton-hub-catalog: "Tekton"
    #@schema/desc "The default Artifact Hub Task catalog from where to pull the resource."
    default-artifact-hub-task-catalog: "tekton-catalog-tasks"
    #@schema/desc "The default Artifact Hub Pipeline catalog from where to pull the resource."
    default-artifact-hub-pipeline-catalog: "tekton-catalog-pipelines"
    #@schema/desc "The default resource kind to fetch."
    #@schema/validation one_of=["pipeline", "task"]
    default-kind: "task"
    #@schema/desc "The default hub from where to pull the resource."
    #@schema/validation one_of=["artifact", "tekton"]
    default-type: "artifact"

  #@schema/desc "Feature flags configuration stored in the `resolvers-feature-flags` ConfigMap."
  resolvers-feature-flags:
    #@schema/desc "Setting this flag to `true` enables remote resolution of Tekton OCI bundles."
    enable-bundles-resolver: "true"
    #@schema/desc "Setting this flag to `true` enables remote resolution of tasks and pipelines via the Tekton Hub."
    enable-hub-resolver: "true"
    #@schema/desc "Setting this flag to `true` enables remote resolution of tasks and pipelines from Git repositories."
    enable-git-resolver: "true"
    #@schema/desc "Setting this flag to `true` enables remote resolution of tasks and pipelines from other namespaces within the cluster."
    enable-cluster-resolver: "true"
